### ISSUE TITLE
Can't add phone_number button

### ISSUE THREAD

**Issue by kenzouno1** [botman/driver-facebook#20]
I want add hot line to button but not working. This only return `tel:` and empty number
Here is my code
``` 
$bot->reply(ButtonTemplate::create('Gọi điện cho tổng đài hotline')
            ->addButton(ElementButton::create('Hotline 1')->type('phone_number')->payload('+PHONE_NUMBER'))
            ->addButton(ElementButton::create('Hotline 2')->type('phone_number')->payload('+PHONE_NUMBER'))
        );
```
And Here is i'm debug buttons template
```
[2017-09-08 09:13:51] local.DEBUG: array (
  'type' => 'phone_number',
  'title' => 'Hotline 1',
  'url' => NULL,
)  
[2017-09-08 09:13:51] local.DEBUG: array (
  'type' => 'phone_number',
  'title' => 'Hotline 2',
  'url' => NULL,
)  
```
but template phone number of facebook is

```
 {
          "type":"phone_number",
          "title":"Call Representative",
          "payload":"+15105551234"
  }
```

**Comment by kenzouno1** [comment]
i'm fixed with edit code in `src/Extentions/ElementButton.php` line `155` 
replace
` if ($this->type === self::TYPE_POSTBACK) ` to `if ($this->type === self::TYPE_POSTBACK || $this->type === self::TYPE_CALL  )`

**Comment by mpociot** [comment]
@kenzouno1 
Can you provide a pull request with your fix? That would be great!

**Comment by kenzouno1** [comment]
Yes. I do
