### ISSUE TITLE
Error when the bot subscribes to "message_echoes"

### ISSUE THREAD

**Issue by johntiror** [botman/driver-facebook#22]
driver version: 1.0.2

If in the facebook bot developer console you subscribe the bot also to the "message_echoes", after the first message the bot will sto working since the driver does not support the echoes. 

The error returned is:
Error sending payload: (#100) Tried accessing nonexisting field (first_name) on node type (Page) (500 Internal Server Error)

<img width="790" alt="schermata 2017-09-09 alle 21 50 59" src="https://user-images.githubusercontent.com/3677019/30243421-01201dda-95a9-11e7-9578-13b2e9891907.png">

in order to reproduce simply subscribe the bot to "message_echoes" and than send a couple of messages, the bot will never answer the second message. Note: subscribing to a new field has a lag (few mins), keep in mind in case the bot will continue working.

**Comment by MohamedShetewy** [comment]
still this problem with me where botman not support event message_echoes 
how  solve it ?
