### ISSUE TITLE
 Composer is disabled for this thread 

### ISSUE THREAD

**Issue by abr4xas** [botman/driver-facebook#47]
Hi there, 
One of my page in which I started using Botman now shows `Composer is disabled for this thread ` When persisten menu is active.
How to fix it?

**Comment by mpociot** [comment]
According to Google, the error comes from Chatfuel. So I doubt that this has anything to do with BotMan.

**Comment by abr4xas** [comment]
I just realized that you have to change a value in the configuration file that is located in `config/botman/facebook.php` 

`'composer_input_disabled' => 'false',`
