### ISSUE TITLE
Can not install on laravel 5.6

### ISSUE THREAD

**Issue by taimaiduc** [botman/driver-facebook#61]
Type error: Argument 1 passed to Illuminate\Routing\Router::sortMiddleware() must be an instance of Illuminate\Support\Collection, instance of Tightenco\Collect\Support\Collection given, called in /vendor/laravel/framework/src/Illuminate/Routing/Router.php on line 676

**Comment by mpociot** [comment]
This is an issue introduced in the latest release of Laravel (5.6.8) - https://github.com/laravel/framework/issues/23420

You can use 5.6.7 in the meantime.
