### ISSUE TITLE
verifyRequest gets everything, but response is empty (when setting up webhook)

### ISSUE THREAD

**Issue by Chrisgia** [botman/driver-facebook#69]
I can't seem to get the webhook between Messenger and Botman working. I tried it on localhost with ngrok USING THE EXACT SAME SCRIPT and it works, but I need it on my webserver.

I logged the hub_verify_token, hub_mode, and hub_challenge in the verifyRequest method and it gets the right token, hub_mode and hub_challenge, but I always get the "Response does not match challenge, expected value="468366090", received="" " error. 

![webhook_error](https://user-images.githubusercontent.com/14153481/42810789-0d52b98c-89b9-11e8-82bf-0e7a808c7592.png)
![errorlog](https://user-images.githubusercontent.com/14153481/42810888-58c43bac-89b9-11e8-862b-91a145ab3d5c.PNG)

I'm using it without BotMan Studio.

**Comment by christophrumpel** [comment]
Hey @Chrisgia , this is a bit difficult to debug. Also as it works locally it means it must be something with your server or .env settings there.

It seems this is `false` right ?https://github.com/botman/driver-facebook/blob/master/src/FacebookDriver.php#L109

I would check that and see why.

**Comment by sakibulalam** [comment]
@Chrisgia, I have faced this issue as well. After debugging I found out that `$this->config->get('verification')` was returning null and thus [FacebookDriver@verifyRequest](https://github.com/botman/driver-facebook/blob/master/src/FacebookDriver.php#L107) didn't return a response.

The culprit in my case was this [[5.0] Environment variables sometimes return null #8191
](https://github.com/laravel/framework/issues/8191) and you can find details in this (Answer)[https://github.com/laravel/framework/issues/8191#issuecomment-86759287]. This is still a issue in Lavel 5.6.

You can try and setting the app environment to `production` and caching the configuration with `php artisan config:cache`. This solved the problem for me. This would not be a problem in `production` but is a hassle in `development`.

**Comment by christophrumpel** [comment]
I am closing this now due to inactivity. @Chrisgia you can still comment if you found a solution.
