### ISSUE TITLE
getUser not working

### ISSUE THREAD

**Issue by WilliamBlais** [botman/driver-facebook#72]
Hello,

I'm trying to use getUser to eventually get the user id, but I always have this error;

`[2018-07-30 06:29:37] local.ERROR: Error sending payload: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api at /Users/user/www/project/vendor/botman/driver-facebook/src/FacebookDriver.php:475)
[stacktrace]
#0 /Users/user/www/project/vendor/botman/driver-facebook/src/FacebookDriver.php(432): BotMan\\Drivers\\Facebook\\FacebookDriver->throwExceptionIfResponseNotOk(Object(Symfony\\Component\\HttpFoundation\\Response))
#1 /Users/user/www/project/vendor/botman/botman/src/BotMan.php(236): BotMan\\Drivers\\Facebook\\FacebookDriver->getUser(Object(BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage))
#2 /Users/user/www/project/app/Http/Controllers/MessengerController.php(26): BotMan\\BotMan\\BotMan->getUser()
#3 [internal function]: App\\Http\\Controllers\\MessengerController->handle(Object(Illuminate\\Http\\Request))
...
`

I also tried using the dev-master of botman/driver-facebook, still the same result.

Anyone got an idea?

Thanks,
William

**Comment by christophrumpel** [comment]
Hey @WilliamBlais ,
just tried it on the latest version of for me everything is working.

Does receiving messages and replying back with Facebook and your bot work?

**Comment by christophrumpel** [comment]
Ok I know why this is happening. There was a change by Facebook that only allows `name`, `first_name`, `last_name`, `profile_pic` by default. For everything else you need a permission. We need to change that in the driver. https://developers.facebook.com/docs/messenger-platform/identity/user-profile/

**Comment by christophrumpel** [comment]
There has already been a PR for a workarodung #74 . We are also working a new version of the FacebookDriver to change the behaviour due to the new permissions.

**Comment by WilliamBlais** [comment]
@christophrumpel Got it, thank you for your help!

**Comment by christian482** [comment]
i got this error, i cant see the project to update
