### ISSUE TITLE
Working with Facebook Built-in NLP and customized with Wit.ai

### ISSUE THREAD

**Issue by sakibulalam** [botman/driver-facebook#76]
Facebook Built-in NLP and that customized with Wit.ai provides the NLP data with the request. How to define the responses of the bot using these?

**Comment by christophrumpel** [comment]
This not specifically supported in BotMan so far. What you can do is grab the information by getting the full payload of the message with `$bot->getMessage()->getPayload();`.

**Comment by sakibulalam** [comment]
Can this be done with a custom middleware to achieve something described in the documentation ([link](https://botman.io/2.0/nlp))? 
I will parse the payload and set the intent that can be picked up by `$botman->hears()`.
