### ISSUE TITLE
Handover Protocol

### ISSUE THREAD

**Issue by metanite** [botman/driver-facebook#93]
Does botman support facebook handover protocol? I have seen this code in driver-facebook but i don't know how to use this.

`   /**
     * Pass a conversation to the page inbox.
     *
     * @param IncomingMessage $message
     * @param $bot
     * @return Response
     */
    public function handover(IncomingMessage $message, $bot)
    {
        return $this->http->post($this->facebookProfileEndpoint.'me/pass_thread_control?access_token='.$this->config->get('token'), [], [
            'recipient' => [
                'id' => $message->getSender(),
            ],
            'target_app_id' => self::HANDOVER_INBOX_PAGE_ID,
        ]);
    }`

If this is supported how do i use this? thank you

**Comment by Astriel** [comment]
Hey @metanite did you find a way to use it ? 

Found the same function here. I think you have somehow to call the Facebook driver. Then the handover method. The ID will be the one of your page inbox by default. 

You have to attach two parameters, the message and the sender I guess.

**Comment by metanite** [comment]
Yes, but i have to modify the code a little bit to support another target app id since it only uses the inbox page id.

**Comment by xSoulRootx** [comment]
Try in routes/botman.php

$botman->on('request_thread_control', function ($payload, $bot) {
    $bot->handover($bot->getMessage(), $bot);
});

It`s work for me.
PS: You must config in fb page settings.
